Add Push Notification support (CR2483)
iotivity/iotivity-lite pull request #316
Opened 2022-09-17 10:04 UTC by Danielius1922

2022-09-17 10:29 UTC, Danielius1922 commented
@joochlee I had a hard time rebasing and squashing your original branch, so instead I've created a new one and copied the changed files. I've run diff on the branches and they are identical, so it should be OK to merge this one.

2022-09-19 05:19 UTC, joochlee commented
> @joochlee I had a hard time rebasing and squashing your original branch, so instead I've created a new one and copied the changed files. I've run diff on the branches and they are identical, so it should be OK to merge this one.

It looks good, Thank you Daniel ! 👍

2022-09-19 09:12 UTC, jkralik requested changes
pls replace `rsc` by `resource` for API

2022-09-19 10:58 UTC, joochlee commented on apps/docs/push.md
> +	typedef struct oc_pushd_rsc_rep
do you want to change `struct oc_pushd_rsc_rep` into `struct oc_pushd_resource_rep` only, 
or `oc_pushd_rsc_rep_t` into `oc_pushd_resource_rep_t` too ?

2022-09-19 11:22 UTC, joochlee commented on apps/docs/push.md
> +	typedef struct oc_pushd_rsc_rep
fixed:
- `oc_pushd_rsc_rep` => `oc_pushd_resource_rep`
- `oc_pushd_rsc_rep_t` => `oc_pushd_resource_rep_t`

2022-09-19 12:05 UTC, jkralik commented on apps/docs/push.md
> +	typedef struct oc_pushd_rsc_rep
I mean to get rid of `rsc` abbreviation from types and functions in whole PR.

2022-09-19 12:11 UTC, joochlee commented on apps/docs/push.md
> +	typedef struct oc_pushd_rsc_rep
> I mean to get rid of `rsc` abbreviation from types and functions in whole PR.

do you mean that just removing `rsc` from type name ? 
or replacing `rsc` with `resource` ?

I replaced `rsc` with `resource` in whole PR like as follows:
-  `oc_pushd_rsc_rep` => `oc_pushd_resource_rep`
-  `oc_pushd_rsc_rep_t` => `oc_pushd_resource_rep_t`

2022-09-20 09:30 UTC, jkralik commented on apps/docs/push.md
> +	typedef struct oc_pushd_rsc_rep
Please renames macros and function:
```
PUSHCONF_RSC_*
oc_print_pushd_rsc
```

2022-09-26 12:59 UTC, Danielius1922 commented
> Thank you Daniel! +1+1
> 
> I have been busy for other works in last week...

I thought that was the case, but Jozef said that we should merge this today ( well, he actually said that on Friday :D ), so I renamed the public stuff to desired names (and did some other minor stylistic changes). The tests passed, so once Jozef approves I'll merge.
I've also created #319 , so we can fix the issues reported by SonarCloud and clang-tidy and add unit tests.

2022-09-26 13:03 UTC, joochlee commented
> > Thank you Daniel! +1+1
> > I have been busy for other works in last week...
> 
> I thought that was the case, but Jozef said that we should merge this today ( well, he actually said that on Friday :D ), so I renamed the public stuff to desired names (and did some other minor stylistic changes). The tests passed, so once Jozef approves I'll merge. I've also created #319 , so we can fix the issues reported by SonarCloud and clang-tidy and add unit tests.

got it! 😎
Thanks

2022-09-26 13:40 UTC, merged